[package]
name = "omnivox-audio"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
omnivox-core = { path = "../omnivox-core" }
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
rodio = { version = "0.19", default-features = false, features = ["vorbis", "wav"] }

[dev-dependencies]
